
# -*- restclient -*-

#Variables
:port = 8010
:api = http://localhost::port/api/v1
:viewLinkID = 1854e37bba3c023e372b7d930547b7c8
:editLinkID = a49ef12c507ec98527d80db9bba038cc
:unknownLinkID = thisIsNotGonnaWork

# ======== Test Post Creation End-Point ========

# Create post
POST :api/posts
Content-Type: application/json

{
	"title" : "This is the title",
	"body"  : "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
	"scope" : "Private"
}

# Create post with null values
# Reports Error ##############
POST :api/posts
Content-Type: application/json

{
	"title" : "",
	"body"  : "",
	"scope" : ""
}

# Create post with incorrect JSON. The JSON is missing a comma's. 
# Reports error.
POST :api/posts
Content-Type: application/json

{
	"title" : "This is the post"
	"body"  : "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
	"scope" : "Private"
}

# ======== Test Public Posts Retrieval End-Point ========

# Retrieving all posts end point
# Accessing a valid page
# For each post, their title, body, view link, and timestamp is sent by the server
GET :api/posts?page=1


# Retrieving a page outside the bounds
# Returns empty JSON array
GET :api/posts?page=100

# Retrieving something from an invalid page number
# Return error
GET :api/posts?page=:unknownLinkID


# ======== Test Specific Post Retrieval End-Point ========

# Getting the post using its view link
# View link returns the Title, Body and the Timestamp of post creation.  
GET :api/posts/:viewLinkID

# Getting the post using its edit link
# View link returns the Title, Body, post creation timestamp, view link, and edit link.   
GET :api/posts/:editLinkID

# Getting the post with an unknown link
# Returns error
GET :api/posts/:unknownLinkID

# ======== Test Post Updating End-Point ========

# Updating with a view link
# Returns error
POST :api/posts/:viewLinkID
Content-Type: application/json

{
	"title" : "This is the new title", 
	"scope" : "Public"
}

# Updating with an edit link to the post
# Edits the post
POST :api/posts/:editLinkID
Content-Type: application/json

{
	"title" : "This is the new title", 
	"scope" : "Public"
}

# Updating with a unknown link
# Returns error
POST :api/posts/:unknownLinkID
Content-Type: application/json

{
	"title" : "This is the new title", 
	"scope" : "Public"
}

# ======== Test Post Reporting End-Point ========

# Reporting with a view link
# Reports the post
POST :api/posts/report/:viewLinkID
Content-Type: application/json

{
	"reason" : "Inappropriate Content"
}

# Updating with an edit link to the post
# Returns error
POST :api/posts/report/:editLinkID
Content-Type: application/json

{
	"reason" : "Inappropriate Content" 
}


# Updating with a unknown link
# Returns error
POST :api/posts/report/:unknownLinkID
Content-Type: application/json

{
	"reason" : "Inappropriate Content" 
}


# ======== Test Post Deletion End-Point ========

# Deleting the post using its view link
# Returns Error  
DELETE :api/posts/:viewLinkID

# Getting the post using its edit link
# Deletes the post
DELETE :api/posts/:editLinkID

# Getting the post with an unknown link
# Returns error
DELETE :api/posts/:unknownLinkID