
# -*- restclient -*-

# ======== Test Post Creation End-Point ========

# Create post
POST http://localhost:8110/api/v1/posts
Content-Type: application/json

{
	"title" : "This is the title",
	"body"  : "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
	"scope" : "Private"
}

# Create post with null values
# Reports Error ##############
POST http://localhost:8110/api/v1/posts
Content-Type: application/json

{
	"title" : "",
	"body"  : "",
	"scope" : ""
}

# Create post with incorrect JSON. The JSON is missing a comma's. 
# Reports error.
POST http://localhost:8110/api/v1/posts
Content-Type: application/json

{
	"title" : "This is the post"
	"body"  : "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
	"scope" : "Private"
}

# ======== Test Public Posts Retrieval End-Point ========

# Retrieving all posts end point
# Accessing a valid page
# For each post, their title, body, view link, and timestamp is sent by the server
GET http://localhost:8110/api/v1/posts?page=1


# Retrieving a page outside the bounds
# Returns empty JSON array
GET http://localhost:8110/api/v1/posts?page=100

# Retrieving something from an invalid page number
# Return error
GET http://localhost:8110/api/v1/posts?page=thisIDisnotgonnawork


# ======== Test Specific Post Retrieval End-Point ========

# Getting the post using its view link
# View link returns the Title, Body and the Timestamp of post creation.  
GET http://localhost:8110/api/v1/posts/966bdd0474e6744fc6a50eb18e44e0e6

# Getting the post using its edit link
# View link returns the Title, Body, post creation timestamp, view link, and edit link.   
GET http://localhost:8110/api/v1/posts/a49ef12c507ec98527d80db9bba038cc

# Getting the post with an unknown link
# Returns error
GET http://localhost:8110/api/v1/posts/thislinkisnotgonnawork


# ======== Test Post Updating End-Point ========

# Updating with a view link
# Returns error
POST http://localhost:8110/api/v1/posts/1854e37bba3c023e372b7d930547b7c8
Content-Type: application/json

{
	"title" : "This is the new title", 
	"scope" : "Public"
}

# Updating with an edit link to the post
# Edits the post
POST http://localhost:8110/api/v1/posts/a49ef12c507ec98527d80db9bba038cc
Content-Type: application/json

{
	"title" : "This is the new title", 
	"scope" : "Public"
}

# Updating with a unknown link
# Returns error
POST http://localhost:8110/api/v1/posts/thislinkisnotgonnawork
Content-Type: application/json

{
	"title" : "This is the new title", 
	"scope" : "Public"
}

# ======== Test Post Reporting End-Point ========

# Reporting with a view link
# Reports the post
POST http://localhost:8110/api/v1/posts/report/1854e37bba3c023e372b7d930547b7c8
Content-Type: application/json

{
	"reason" : "Inappropriate Content"
}

# Updating with an edit link to the post
# Returns error
POST http://localhost:8110/api/v1/posts/report/a49ef12c507ec98527d80db9bba038cc
Content-Type: application/json

{
	"reason" : "Inappropriate Content" 
}


# Updating with a unknown link
# Returns error
POST http://localhost:8110/api/v1/posts/report/thislinkisnotgonnawork
Content-Type: application/json

{
	"reason" : "Inappropriate Content" 
}


# ======== Test Post Deletion End-Point ========

# Deleting the post using its view link
# Returns Error  
DELETE http://localhost:8110/api/v1/posts/1854e37bba3c023e372b7d930547b7c8

# Getting the post using its edit link
# Deletes the post
DELETE http://localhost:8110/api/v1/posts/6bfd47333328551745adf34dbb39c7fa

# Getting the post with an unknown link
# Returns error
DELETE http://localhost:8110/api/v1/posts/thislinkisnotgonnawork